spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_DB_HOST}/${PROD_MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_MYSQL_DB_USERNAME}
    password: ${PROD_MYSQL_DB_PASSWORD}