spring:
  datasource:
    url: jdbc:mysql://${LOCAL_MYSQL_DB_HOST}/${LOCAL_MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_MYSQL_DB_USERNAME}
    password: ${LOCAL_MYSQL_DB_PASSWORD}