minio:
  url: https://selp-minio.jaeyoung2.duckdns.org
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: prod
  region: ap-northeast-2
  presign:
    expiration-seconds: ${PROD_PRESIGNED_URL_SECONDS}   # 6시간 = 6*3600

springdoc:
  swagger-ui:
    url: https://selp-backend.jaeyoung2.duckdns.org

spring:
  datasource:
    url: jdbc:mysql://selp-mysql-db:3306/selp-prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_MYSQL_DB_USERNAME}
    password: ${PROD_MYSQL_DB_PASSWORD}

  ai:
    vector-store:
      chroma:
        client:
          host: http://selp-chroma-db
          port: 8000