minio:
  url: https://selp-minio.jaeyoung2.duckdns.org
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: dev
  region: ap-northeast-2
  presign:
    expiration-seconds: ${LOCAL_PRESIGNED_URL_SECONDS}

spring:
  datasource:
    url: jdbc:mysql://${LOCAL_MYSQL_DB_HOST}/selp_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_MYSQL_DB_USERNAME}
    password: ${LOCAL_MYSQL_DB_PASSWORD}

  ai:
    vector-store:
      chroma:
        client:
          host: https://selp-chroma.jaeyoung2.duckdns.org
          port: 443
