server:
  port: 8080

logging:
  level:
    root: INFO

#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: org.fadak.selp.selpbackend.domain.dto


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}
  signup-token-expiration-minutes: ${SIGNUP_TOKEN_EXPIRATION_MINUTES}


spring:
  application:
    name: selp-backend
  ai:
    openai:
      api-key: ${OPEN_AI_KEY_1}
    vector-store:
      chroma:
        tenant-name: SpringAiTenant
        database-name: SpringAiDatabase
        collection-name: SpringAiCollection
        client:
          key-token: ${PROD_CHROMA_TOKEN}

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SERVER_DOMAIN}/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
